#!/bin/bash

SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LISTS_DIR="$SCRIPTS_DIR/Lists"

if [ "$(whoami)" != "root" ]
then
  echo "You have to run as Superuser!"
  exit 1
fi

for cmd in rm; do
  if ! command -v "$cmd" &> /dev/null; then
    echo "$cmd is missing!"
    exit 1
  fi
done

$SCRIPTS_DIR/Remove/$1
rm -rf "$SCRIPTS_DIR/Remove/$1"
rm -rf "$SCRIPTS_DIR/InstallLists/$1.list"
