#!/bin/bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd $DIR
SCRIPT_PACKAGE_TOOL="../scripts/ScriptPackageTool"

case "$1" in
    install)
        chmod +x $SCRIPT_PACKAGE_TOOL/InstallMgr &> /dev/null
        $SCRIPT_PACKAGE_TOOL/InstallMgr $2
        ;;
    remove)
        chmod +x $SCRIPT_PACKAGE_TOOL/RemoveMgr &> /dev/null
        $SCRIPT_PACKAGE_TOOL/RemoveMgr $2
        ;;
    update)
        chmod +x $SCRIPT_PACKAGE_TOOL/UpdateMgr &> /dev/null
        $SCRIPT_PACKAGE_TOOL/UpdateMgr $2
        ;;
    search)
        chmod +x $SCRIPT_PACKAGE_TOOL/SearchMgr &> /dev/null
        $SCRIPT_PACKAGE_TOOL/SearchMgr
        ;;
    *)
        echo
        echo "Script Package Tool V0.2 By MrR736 : 2024-10-24"
        echo
        echo "Usage: spt <Commands>"
        echo
        echo "<Commands>"
        echo "  Install : Install Script Packages"
        echo "  Remove : Remove Script Packages"
        echo "   -l : List Script Packages"
        echo "  Search : Search Script Packages"
        echo "  Update : Update Script Packages"
        echo "   -f : Update Full"
        ;;
esac
